config: default
ctx_size: 512
db_path: database.db
debug: false
host: localhost
language: en-US
model: gpt4all-lora-quantized-ggml.bin
n_predict: 256
nb_messages_to_remember: 5
personality: gpt4all_chatbot
port: 9600
repeat_last_n: 40
repeat_penalty: 1.3
seed: 0
temp: 0.1
top_k: 40
top_p: 0.95
voice: ""
